# The base URL is used for testing purposes only.
#base_url = "http://localhost.com:9999"

# Proxy server configuration.
# You should use a TLS certificate or run it behind a reverse proxy that queries a certificate for you.
[server]
host = ":80"
write_timeout = 5
read_timeout = 5
#tls = true
#tls_cert = "path/to/cert_file"
#tls_key = "path/to/key_file

# List of clients to send data to.
# The client ID can be left empty if you use an access token instead of oAuth.
[[clients]]
    id = "your-client-id"
    secret = "your-client-secret"
    hostname = "example.com"

#[[clients]]
#    id = "your-client-id"
#    secret = "your-client-secret"
#    hostname = "example.com"
