base_url = "http://localhost.com:9999"

[server]
host = ":2345"
write_timeout = 5
read_timeout = 5

[[clients]]
    id = "zDgQ95gmKy4lPm27n4K6AR17yT9SKe9l"
    secret = "osHgq5FJx5b2KWg0lwwQFl5xz1H5E6O8n1JmLAOOBfqbnVmJulQ5cPqnLXMRUstm"
    hostname = "localhost.com"
